# Environments
# APP_TAG=0.0.1 - override CI_COMMIT_TAG var, application release version

variables:
  - &debian_image 'public.ecr.aws/docker/library/debian:bookworm-slim'
  - &golang_image 'public.ecr.aws/docker/library/golang:1.22.4-bookworm'
  - &kaniko_image "gcr.io/kaniko-project/executor:v1.23.1-debug"

when:
  - branch: main
    event:
      - manual
      - push
  - branch:
      exclude: main
    event:
      - manual
      - tag

steps:
  set-env:
    image: *debian_image
    commands:
      - .cicd/set-env.sh
  vendor:
    image: *golang_image
    commands:
      - .cicd/vendor.sh
  build:
    image: *golang_image
    commands:
      - .cicd/build.sh
  image:
    image: *kaniko_image
    environment:
      DOCKER_USR:
        from_secret: fb_harbor_usr
      DOCKER_PWD:
        from_secret: fb_harbor_pwd
    commands:
      - .cicd/set-docker-auth.sh
      - .cicd/image.sh
